# Generated by Django 3.2.8 on 2021-11-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('time_frame', models.CharField(blank=True, max_length=250)),
                ('goals', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
