# Generated by Django 3.2.8 on 2021-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recievedemail',
            old_name='message',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='recievedemail',
            old_name='subject',
            new_name='time_frame',
        ),
        migrations.AddField(
            model_name='recievedemail',
            name='type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
